resource_group_name       = "devmyrg"
location                  = "East US"
storage_account_name      = "devmysa"
container_name            = "devmycont"
blob_name                 = "devmyblob.zip"
source_file               = "./modules/azure_storage_account/test.txt"
blob_type                 = "Block"
